import "@/app/globals.css";

import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";

import { Providers } from "./providers";

export const metadata: Metadata = {
	title: "CloudVault",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className={GeistSans.className}>
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
